export const productsTest = [
    {
      asin: "B0CWHXVLXG",
      product_title: "Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green",
      product_price: "$149.99",
      product_original_price: "$199.99",
      currency: "USD",
      product_star_rating: "4.1",
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0CWHXVLXG",
      product_photo: "https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg",
      product_num_offers: 2,
      product_minimum_offer_price: "$130.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "3K+ bought in past month",
      delivery: "FREE delivery Mon, Dec 16 Or fastest delivery Fri, Dec 13 Arrives before Christmas",
      has_variations: true
    },
    {
      asin: "B0CSB14R7J",
      product_title: "Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black",
      product_price: "$147.22",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.3",
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0CSB14R7J",
      product_photo: "https://m.media-amazon.com/images/I/515zGEaozeL._AC_UY654_FMwebp_QL65_.jpg",
      product_num_offers: 16,
      product_minimum_offer_price: "$134.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "3K+ bought in past month",
      delivery: "FREE delivery Wed, Dec 18 Or fastest delivery Sat, Dec 14 Arrives before Christmas",
      has_variations: false
    },
    {
      asin: "B08PP5MSVB",
      product_title: "Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)",
      product_price: "$268.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.1",
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B08PP5MSVB",
      product_photo: "https://m.media-amazon.com/images/I/51fYXSnSu9L._AC_UY654_FMwebp_QL65_.jpg",
      product_num_offers: 19,
      product_minimum_offer_price: "$233.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "6K+ bought in past month",
      delivery: "FREE delivery Dec 12 - 16 Arrives before Christmas",
      has_variations: true
    },
    {
      asin: "B0CP6DDN1H",
      product_title: "Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue",
      product_price: "$109.99",
      product_original_price: "$149.99",
      currency: "USD",
      product_star_rating: "4",
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0CP6DDN1H",
      product_photo: "https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg",
      product_num_offers: 3,
      product_minimum_offer_price: "$66.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "6K+ bought in past month",
      delivery: "FREE delivery Tue, Dec 17 Or fastest delivery Fri, Dec 13 Arrives before Christmas",
      has_variations: true
    },
    {
      asin: "B0CSB22F9C",
      product_title: "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
      product_price: "$155.57",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.2",
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0CSB22F9C",
      product_photo: "https://m.media-amazon.com/images/I/51rp0nqaPoL._AC_UY654_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$155.57",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      product_availability: "Only 15 left in stock - order soon.",
      climate_pledge_friendly: false,
      sales_volume: "5K+ bought in past month",
      delivery: "FREE delivery Sat, Dec 21 Or fastest delivery Tue, Dec 17 Arrives before ChristmasOnly 15 left in stock - order soon.",
      has_variations: false
    },
    // You can continue to add more products in the same way...
  ];